//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18010
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactInformations.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CountryCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CountryCodes() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContactInformations.Properties.CountryCodes", typeof(CountryCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Andorra ähnelt.
        /// </summary>
        internal static string AD {
            get {
                return ResourceManager.GetString("AD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die United Arab Emirates ähnelt.
        /// </summary>
        internal static string AE {
            get {
                return ResourceManager.GetString("AE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Afghanistan ähnelt.
        /// </summary>
        internal static string AF {
            get {
                return ResourceManager.GetString("AF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Antigua and Barbuda ähnelt.
        /// </summary>
        internal static string AG {
            get {
                return ResourceManager.GetString("AG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anguilla ähnelt.
        /// </summary>
        internal static string AI {
            get {
                return ResourceManager.GetString("AI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Albania ähnelt.
        /// </summary>
        internal static string AL {
            get {
                return ResourceManager.GetString("AL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Armenia ähnelt.
        /// </summary>
        internal static string AM {
            get {
                return ResourceManager.GetString("AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Netherlands Antilles ähnelt.
        /// </summary>
        internal static string AN {
            get {
                return ResourceManager.GetString("AN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Angola ähnelt.
        /// </summary>
        internal static string AO {
            get {
                return ResourceManager.GetString("AO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ARIPO ähnelt.
        /// </summary>
        internal static string AP {
            get {
                return ResourceManager.GetString("AP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Argentina ähnelt.
        /// </summary>
        internal static string AR {
            get {
                return ResourceManager.GetString("AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Austria ähnelt.
        /// </summary>
        internal static string AT {
            get {
                return ResourceManager.GetString("AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Australia ähnelt.
        /// </summary>
        internal static string AU {
            get {
                return ResourceManager.GetString("AU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aruba ähnelt.
        /// </summary>
        internal static string AW {
            get {
                return ResourceManager.GetString("AW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Azerbaijan ähnelt.
        /// </summary>
        internal static string AZ {
            get {
                return ResourceManager.GetString("AZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bosnia and Herzegovina ähnelt.
        /// </summary>
        internal static string BA {
            get {
                return ResourceManager.GetString("BA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Barbados ähnelt.
        /// </summary>
        internal static string BB {
            get {
                return ResourceManager.GetString("BB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bangladesh ähnelt.
        /// </summary>
        internal static string BD {
            get {
                return ResourceManager.GetString("BD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Belgium ähnelt.
        /// </summary>
        internal static string BE {
            get {
                return ResourceManager.GetString("BE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Burkina Faso ähnelt.
        /// </summary>
        internal static string BF {
            get {
                return ResourceManager.GetString("BF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bulgaria ähnelt.
        /// </summary>
        internal static string BG {
            get {
                return ResourceManager.GetString("BG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bahrain ähnelt.
        /// </summary>
        internal static string BH {
            get {
                return ResourceManager.GetString("BH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Burundi ähnelt.
        /// </summary>
        internal static string BI {
            get {
                return ResourceManager.GetString("BI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benin ähnelt.
        /// </summary>
        internal static string BJ {
            get {
                return ResourceManager.GetString("BJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bermuda ähnelt.
        /// </summary>
        internal static string BM {
            get {
                return ResourceManager.GetString("BM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Brunei Darussalam ähnelt.
        /// </summary>
        internal static string BN {
            get {
                return ResourceManager.GetString("BN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bolivia ähnelt.
        /// </summary>
        internal static string BO {
            get {
                return ResourceManager.GetString("BO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Brazil ähnelt.
        /// </summary>
        internal static string BR {
            get {
                return ResourceManager.GetString("BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bahamas ähnelt.
        /// </summary>
        internal static string BS {
            get {
                return ResourceManager.GetString("BS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bhutan ähnelt.
        /// </summary>
        internal static string BT {
            get {
                return ResourceManager.GetString("BT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Burma ähnelt.
        /// </summary>
        internal static string BU {
            get {
                return ResourceManager.GetString("BU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bouvet Island ähnelt.
        /// </summary>
        internal static string BV {
            get {
                return ResourceManager.GetString("BV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Botswana ähnelt.
        /// </summary>
        internal static string BW {
            get {
                return ResourceManager.GetString("BW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BBM and BBDM ähnelt.
        /// </summary>
        internal static string BX {
            get {
                return ResourceManager.GetString("BX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Belarus ähnelt.
        /// </summary>
        internal static string BY {
            get {
                return ResourceManager.GetString("BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Belize ähnelt.
        /// </summary>
        internal static string BZ {
            get {
                return ResourceManager.GetString("BZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Canada ähnelt.
        /// </summary>
        internal static string CA {
            get {
                return ResourceManager.GetString("CA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Central African Republic ähnelt.
        /// </summary>
        internal static string CF {
            get {
                return ResourceManager.GetString("CF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Congo ähnelt.
        /// </summary>
        internal static string CG {
            get {
                return ResourceManager.GetString("CG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Switzerland ähnelt.
        /// </summary>
        internal static string CH {
            get {
                return ResourceManager.GetString("CH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cote d&apos;Ivoire ähnelt.
        /// </summary>
        internal static string CI {
            get {
                return ResourceManager.GetString("CI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cook Islands ähnelt.
        /// </summary>
        internal static string CK {
            get {
                return ResourceManager.GetString("CK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chile ähnelt.
        /// </summary>
        internal static string CL {
            get {
                return ResourceManager.GetString("CL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cameroon ähnelt.
        /// </summary>
        internal static string CM {
            get {
                return ResourceManager.GetString("CM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die China ähnelt.
        /// </summary>
        internal static string CN {
            get {
                return ResourceManager.GetString("CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Colombia ähnelt.
        /// </summary>
        internal static string CO {
            get {
                return ResourceManager.GetString("CO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Costa Rica ähnelt.
        /// </summary>
        internal static string CR {
            get {
                return ResourceManager.GetString("CR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Czechoslovakia ähnelt.
        /// </summary>
        internal static string CS {
            get {
                return ResourceManager.GetString("CS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cuba ähnelt.
        /// </summary>
        internal static string CU {
            get {
                return ResourceManager.GetString("CU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cape Verde ähnelt.
        /// </summary>
        internal static string CV {
            get {
                return ResourceManager.GetString("CV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cyprus ähnelt.
        /// </summary>
        internal static string CY {
            get {
                return ResourceManager.GetString("CY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Czech Republic ähnelt.
        /// </summary>
        internal static string CZ {
            get {
                return ResourceManager.GetString("CZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die East Germany ähnelt.
        /// </summary>
        internal static string DD {
            get {
                return ResourceManager.GetString("DD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Germany ähnelt.
        /// </summary>
        internal static string DE {
            get {
                return ResourceManager.GetString("DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Djibouti ähnelt.
        /// </summary>
        internal static string DJ {
            get {
                return ResourceManager.GetString("DJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Denmark ähnelt.
        /// </summary>
        internal static string DK {
            get {
                return ResourceManager.GetString("DK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dominica ähnelt.
        /// </summary>
        internal static string DM {
            get {
                return ResourceManager.GetString("DM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dominican Republic ähnelt.
        /// </summary>
        internal static string DO {
            get {
                return ResourceManager.GetString("DO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Algeria ähnelt.
        /// </summary>
        internal static string DZ {
            get {
                return ResourceManager.GetString("DZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EAPO ähnelt.
        /// </summary>
        internal static string EA {
            get {
                return ResourceManager.GetString("EA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ecuador ähnelt.
        /// </summary>
        internal static string EC {
            get {
                return ResourceManager.GetString("EC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Estonia ähnelt.
        /// </summary>
        internal static string EE {
            get {
                return ResourceManager.GetString("EE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Egypt ähnelt.
        /// </summary>
        internal static string EG {
            get {
                return ResourceManager.GetString("EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Western Sahara ähnelt.
        /// </summary>
        internal static string EH {
            get {
                return ResourceManager.GetString("EH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OHIM ähnelt.
        /// </summary>
        internal static string EM {
            get {
                return ResourceManager.GetString("EM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EPO ähnelt.
        /// </summary>
        internal static string EP {
            get {
                return ResourceManager.GetString("EP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spain ähnelt.
        /// </summary>
        internal static string ES {
            get {
                return ResourceManager.GetString("ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ethiopia ähnelt.
        /// </summary>
        internal static string ET {
            get {
                return ResourceManager.GetString("ET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Finland ähnelt.
        /// </summary>
        internal static string FI {
            get {
                return ResourceManager.GetString("FI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fiji ähnelt.
        /// </summary>
        internal static string FJ {
            get {
                return ResourceManager.GetString("FJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Falkland Island ähnelt.
        /// </summary>
        internal static string FK {
            get {
                return ResourceManager.GetString("FK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Micronesia ähnelt.
        /// </summary>
        internal static string FM {
            get {
                return ResourceManager.GetString("FM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Faroe Islands ähnelt.
        /// </summary>
        internal static string FO {
            get {
                return ResourceManager.GetString("FO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die France ähnelt.
        /// </summary>
        internal static string FR {
            get {
                return ResourceManager.GetString("FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gabon ähnelt.
        /// </summary>
        internal static string GA {
            get {
                return ResourceManager.GetString("GA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die United Kingdom ähnelt.
        /// </summary>
        internal static string GB {
            get {
                return ResourceManager.GetString("GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grenada ähnelt.
        /// </summary>
        internal static string GD {
            get {
                return ResourceManager.GetString("GD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Georgia ähnelt.
        /// </summary>
        internal static string GE {
            get {
                return ResourceManager.GetString("GE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ghana ähnelt.
        /// </summary>
        internal static string GH {
            get {
                return ResourceManager.GetString("GH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gibraltar ähnelt.
        /// </summary>
        internal static string GI {
            get {
                return ResourceManager.GetString("GI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Greenland ähnelt.
        /// </summary>
        internal static string GL {
            get {
                return ResourceManager.GetString("GL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gambia ähnelt.
        /// </summary>
        internal static string GM {
            get {
                return ResourceManager.GetString("GM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Guinea ähnelt.
        /// </summary>
        internal static string GN {
            get {
                return ResourceManager.GetString("GN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Equatorial Guinea ähnelt.
        /// </summary>
        internal static string GQ {
            get {
                return ResourceManager.GetString("GQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Greece ähnelt.
        /// </summary>
        internal static string GR {
            get {
                return ResourceManager.GetString("GR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die South Georgia and The South Sandwich Islands ähnelt.
        /// </summary>
        internal static string GS {
            get {
                return ResourceManager.GetString("GS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Guatemala ähnelt.
        /// </summary>
        internal static string GT {
            get {
                return ResourceManager.GetString("GT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Guinea-Bissau ähnelt.
        /// </summary>
        internal static string GW {
            get {
                return ResourceManager.GetString("GW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Guyana ähnelt.
        /// </summary>
        internal static string GY {
            get {
                return ResourceManager.GetString("GY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hong Kong ähnelt.
        /// </summary>
        internal static string HK {
            get {
                return ResourceManager.GetString("HK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Honduras ähnelt.
        /// </summary>
        internal static string HN {
            get {
                return ResourceManager.GetString("HN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Croatia ähnelt.
        /// </summary>
        internal static string HR {
            get {
                return ResourceManager.GetString("HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Haiti ähnelt.
        /// </summary>
        internal static string HT {
            get {
                return ResourceManager.GetString("HT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hungary ähnelt.
        /// </summary>
        internal static string HU {
            get {
                return ResourceManager.GetString("HU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Volta ähnelt.
        /// </summary>
        internal static string HV {
            get {
                return ResourceManager.GetString("HV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IIB ähnelt.
        /// </summary>
        internal static string IB {
            get {
                return ResourceManager.GetString("IB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Indonesia ähnelt.
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ireland ähnelt.
        /// </summary>
        internal static string IE {
            get {
                return ResourceManager.GetString("IE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Israel ähnelt.
        /// </summary>
        internal static string IL {
            get {
                return ResourceManager.GetString("IL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die India ähnelt.
        /// </summary>
        internal static string IN {
            get {
                return ResourceManager.GetString("IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Iraq ähnelt.
        /// </summary>
        internal static string IQ {
            get {
                return ResourceManager.GetString("IQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Iran ähnelt.
        /// </summary>
        internal static string IR {
            get {
                return ResourceManager.GetString("IR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Iceland ähnelt.
        /// </summary>
        internal static string IS {
            get {
                return ResourceManager.GetString("IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Italy ähnelt.
        /// </summary>
        internal static string IT {
            get {
                return ResourceManager.GetString("IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jamaica ähnelt.
        /// </summary>
        internal static string JM {
            get {
                return ResourceManager.GetString("JM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jordan ähnelt.
        /// </summary>
        internal static string JO {
            get {
                return ResourceManager.GetString("JO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Japan ähnelt.
        /// </summary>
        internal static string JP {
            get {
                return ResourceManager.GetString("JP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kenya ähnelt.
        /// </summary>
        internal static string KE {
            get {
                return ResourceManager.GetString("KE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kyrgyzstan ähnelt.
        /// </summary>
        internal static string KG {
            get {
                return ResourceManager.GetString("KG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kampuchea ähnelt.
        /// </summary>
        internal static string KH {
            get {
                return ResourceManager.GetString("KH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kiribati ähnelt.
        /// </summary>
        internal static string KI {
            get {
                return ResourceManager.GetString("KI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comoros ähnelt.
        /// </summary>
        internal static string KM {
            get {
                return ResourceManager.GetString("KM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saint Kitts and Nevis ähnelt.
        /// </summary>
        internal static string KN {
            get {
                return ResourceManager.GetString("KN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die North Korea ähnelt.
        /// </summary>
        internal static string KP {
            get {
                return ResourceManager.GetString("KP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die South Korea ähnelt.
        /// </summary>
        internal static string KR {
            get {
                return ResourceManager.GetString("KR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kuwait ähnelt.
        /// </summary>
        internal static string KW {
            get {
                return ResourceManager.GetString("KW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cayman Islands ähnelt.
        /// </summary>
        internal static string KY {
            get {
                return ResourceManager.GetString("KY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kazakhstan ähnelt.
        /// </summary>
        internal static string KZ {
            get {
                return ResourceManager.GetString("KZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Laos ähnelt.
        /// </summary>
        internal static string LA {
            get {
                return ResourceManager.GetString("LA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lebanon ähnelt.
        /// </summary>
        internal static string LB {
            get {
                return ResourceManager.GetString("LB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saint Lucia ähnelt.
        /// </summary>
        internal static string LC {
            get {
                return ResourceManager.GetString("LC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Liechtenstein ähnelt.
        /// </summary>
        internal static string LI {
            get {
                return ResourceManager.GetString("LI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sri Lanka ähnelt.
        /// </summary>
        internal static string LK {
            get {
                return ResourceManager.GetString("LK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Liberia ähnelt.
        /// </summary>
        internal static string LR {
            get {
                return ResourceManager.GetString("LR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lesotho ähnelt.
        /// </summary>
        internal static string LS {
            get {
                return ResourceManager.GetString("LS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lithuania ähnelt.
        /// </summary>
        internal static string LT {
            get {
                return ResourceManager.GetString("LT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Luxembourg ähnelt.
        /// </summary>
        internal static string LU {
            get {
                return ResourceManager.GetString("LU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Libya ähnelt.
        /// </summary>
        internal static string LY {
            get {
                return ResourceManager.GetString("LY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Morocco ähnelt.
        /// </summary>
        internal static string MA {
            get {
                return ResourceManager.GetString("MA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monaco ähnelt.
        /// </summary>
        internal static string MC {
            get {
                return ResourceManager.GetString("MC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Moldova ähnelt.
        /// </summary>
        internal static string MD {
            get {
                return ResourceManager.GetString("MD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Madagascar ähnelt.
        /// </summary>
        internal static string MG {
            get {
                return ResourceManager.GetString("MG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Marshall Islands ähnelt.
        /// </summary>
        internal static string MH {
            get {
                return ResourceManager.GetString("MH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Macedonia ähnelt.
        /// </summary>
        internal static string MK {
            get {
                return ResourceManager.GetString("MK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mali ähnelt.
        /// </summary>
        internal static string ML {
            get {
                return ResourceManager.GetString("ML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Myanmar ähnelt.
        /// </summary>
        internal static string MM {
            get {
                return ResourceManager.GetString("MM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mongolia ähnelt.
        /// </summary>
        internal static string MN {
            get {
                return ResourceManager.GetString("MN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Macao ähnelt.
        /// </summary>
        internal static string MO {
            get {
                return ResourceManager.GetString("MO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Northern Mariana Islands ähnelt.
        /// </summary>
        internal static string MP {
            get {
                return ResourceManager.GetString("MP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mauritania ähnelt.
        /// </summary>
        internal static string MR {
            get {
                return ResourceManager.GetString("MR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Montserrat ähnelt.
        /// </summary>
        internal static string MS {
            get {
                return ResourceManager.GetString("MS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Malta ähnelt.
        /// </summary>
        internal static string MT {
            get {
                return ResourceManager.GetString("MT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mauritius ähnelt.
        /// </summary>
        internal static string MU {
            get {
                return ResourceManager.GetString("MU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maldives ähnelt.
        /// </summary>
        internal static string MV {
            get {
                return ResourceManager.GetString("MV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Malawi ähnelt.
        /// </summary>
        internal static string MW {
            get {
                return ResourceManager.GetString("MW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mexico ähnelt.
        /// </summary>
        internal static string MX {
            get {
                return ResourceManager.GetString("MX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Malaysia ähnelt.
        /// </summary>
        internal static string MY {
            get {
                return ResourceManager.GetString("MY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mozambique ähnelt.
        /// </summary>
        internal static string MZ {
            get {
                return ResourceManager.GetString("MZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Namibia ähnelt.
        /// </summary>
        internal static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Niger ähnelt.
        /// </summary>
        internal static string NE {
            get {
                return ResourceManager.GetString("NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nigeria ähnelt.
        /// </summary>
        internal static string NG {
            get {
                return ResourceManager.GetString("NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nicaragua ähnelt.
        /// </summary>
        internal static string NI {
            get {
                return ResourceManager.GetString("NI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Netherlands(Holland) ähnelt.
        /// </summary>
        internal static string NL {
            get {
                return ResourceManager.GetString("NL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Norway ähnelt.
        /// </summary>
        internal static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nepal ähnelt.
        /// </summary>
        internal static string NP {
            get {
                return ResourceManager.GetString("NP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nauru ähnelt.
        /// </summary>
        internal static string NR {
            get {
                return ResourceManager.GetString("NR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Zealand ähnelt.
        /// </summary>
        internal static string NZ {
            get {
                return ResourceManager.GetString("NZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OAPI ähnelt.
        /// </summary>
        internal static string OA {
            get {
                return ResourceManager.GetString("OA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Oman ähnelt.
        /// </summary>
        internal static string OM {
            get {
                return ResourceManager.GetString("OM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Panama ähnelt.
        /// </summary>
        internal static string PA {
            get {
                return ResourceManager.GetString("PA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Peru ähnelt.
        /// </summary>
        internal static string PE {
            get {
                return ResourceManager.GetString("PE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Papua New Guinea ähnelt.
        /// </summary>
        internal static string PG {
            get {
                return ResourceManager.GetString("PG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Philippines ähnelt.
        /// </summary>
        internal static string PH {
            get {
                return ResourceManager.GetString("PH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pakistan ähnelt.
        /// </summary>
        internal static string PK {
            get {
                return ResourceManager.GetString("PK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Poland ähnelt.
        /// </summary>
        internal static string PL {
            get {
                return ResourceManager.GetString("PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Portugal ähnelt.
        /// </summary>
        internal static string PT {
            get {
                return ResourceManager.GetString("PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paraguay ähnelt.
        /// </summary>
        internal static string PY {
            get {
                return ResourceManager.GetString("PY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Qatar ähnelt.
        /// </summary>
        internal static string QA {
            get {
                return ResourceManager.GetString("QA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rhodesia ähnelt.
        /// </summary>
        internal static string RH {
            get {
                return ResourceManager.GetString("RH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Romania ähnelt.
        /// </summary>
        internal static string RO {
            get {
                return ResourceManager.GetString("RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Russian Federation ähnelt.
        /// </summary>
        internal static string RU {
            get {
                return ResourceManager.GetString("RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rwanda ähnelt.
        /// </summary>
        internal static string RW {
            get {
                return ResourceManager.GetString("RW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saudi Arabia ähnelt.
        /// </summary>
        internal static string SA {
            get {
                return ResourceManager.GetString("SA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Solomon Islands ähnelt.
        /// </summary>
        internal static string SB {
            get {
                return ResourceManager.GetString("SB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Seychelles ähnelt.
        /// </summary>
        internal static string SC {
            get {
                return ResourceManager.GetString("SC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sudan ähnelt.
        /// </summary>
        internal static string SD {
            get {
                return ResourceManager.GetString("SD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sweden ähnelt.
        /// </summary>
        internal static string SE {
            get {
                return ResourceManager.GetString("SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Singapore ähnelt.
        /// </summary>
        internal static string SG {
            get {
                return ResourceManager.GetString("SG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saint Helena ähnelt.
        /// </summary>
        internal static string SH {
            get {
                return ResourceManager.GetString("SH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Slovenia ähnelt.
        /// </summary>
        internal static string SI {
            get {
                return ResourceManager.GetString("SI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Slovakia ähnelt.
        /// </summary>
        internal static string SK {
            get {
                return ResourceManager.GetString("SK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sierra Leone ähnelt.
        /// </summary>
        internal static string SL {
            get {
                return ResourceManager.GetString("SL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die San Marino ähnelt.
        /// </summary>
        internal static string SM {
            get {
                return ResourceManager.GetString("SM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Senegal ähnelt.
        /// </summary>
        internal static string SN {
            get {
                return ResourceManager.GetString("SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Somalia ähnelt.
        /// </summary>
        internal static string SO {
            get {
                return ResourceManager.GetString("SO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suriname ähnelt.
        /// </summary>
        internal static string SR {
            get {
                return ResourceManager.GetString("SR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sao Tome and Principe ähnelt.
        /// </summary>
        internal static string ST {
            get {
                return ResourceManager.GetString("ST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soviet Union ähnelt.
        /// </summary>
        internal static string SU {
            get {
                return ResourceManager.GetString("SU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die El Salvador ähnelt.
        /// </summary>
        internal static string SV {
            get {
                return ResourceManager.GetString("SV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Syria ähnelt.
        /// </summary>
        internal static string SY {
            get {
                return ResourceManager.GetString("SY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Swaziland ähnelt.
        /// </summary>
        internal static string SZ {
            get {
                return ResourceManager.GetString("SZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Turks and Caicos Islands ähnelt.
        /// </summary>
        internal static string TC {
            get {
                return ResourceManager.GetString("TC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chad ähnelt.
        /// </summary>
        internal static string TD {
            get {
                return ResourceManager.GetString("TD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Togo ähnelt.
        /// </summary>
        internal static string TG {
            get {
                return ResourceManager.GetString("TG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thailand ähnelt.
        /// </summary>
        internal static string TH {
            get {
                return ResourceManager.GetString("TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tajikistan ähnelt.
        /// </summary>
        internal static string TJ {
            get {
                return ResourceManager.GetString("TJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Turkmenistan ähnelt.
        /// </summary>
        internal static string TM {
            get {
                return ResourceManager.GetString("TM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tunisia ähnelt.
        /// </summary>
        internal static string TN {
            get {
                return ResourceManager.GetString("TN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tonga ähnelt.
        /// </summary>
        internal static string TO {
            get {
                return ResourceManager.GetString("TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die East Timor ähnelt.
        /// </summary>
        internal static string TP {
            get {
                return ResourceManager.GetString("TP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Turkey ähnelt.
        /// </summary>
        internal static string TR {
            get {
                return ResourceManager.GetString("TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trinidad and Tobago ähnelt.
        /// </summary>
        internal static string TT {
            get {
                return ResourceManager.GetString("TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tuvalu ähnelt.
        /// </summary>
        internal static string TV {
            get {
                return ResourceManager.GetString("TV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Taiwan ähnelt.
        /// </summary>
        internal static string TW {
            get {
                return ResourceManager.GetString("TW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tanzania ähnelt.
        /// </summary>
        internal static string TZ {
            get {
                return ResourceManager.GetString("TZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ukraine ähnelt.
        /// </summary>
        internal static string UA {
            get {
                return ResourceManager.GetString("UA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uganda ähnelt.
        /// </summary>
        internal static string UG {
            get {
                return ResourceManager.GetString("UG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die United States of America ähnelt.
        /// </summary>
        internal static string US {
            get {
                return ResourceManager.GetString("US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uruguay ähnelt.
        /// </summary>
        internal static string UY {
            get {
                return ResourceManager.GetString("UY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uzbekistan ähnelt.
        /// </summary>
        internal static string UZ {
            get {
                return ResourceManager.GetString("UZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vatican City ähnelt.
        /// </summary>
        internal static string VA {
            get {
                return ResourceManager.GetString("VA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saint Vincent and the Grenadines ähnelt.
        /// </summary>
        internal static string VC {
            get {
                return ResourceManager.GetString("VC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Venezuela ähnelt.
        /// </summary>
        internal static string VE {
            get {
                return ResourceManager.GetString("VE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die British Virgin Islands ähnelt.
        /// </summary>
        internal static string VG {
            get {
                return ResourceManager.GetString("VG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vietnam ähnelt.
        /// </summary>
        internal static string VN {
            get {
                return ResourceManager.GetString("VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vanuatu ähnelt.
        /// </summary>
        internal static string VU {
            get {
                return ResourceManager.GetString("VU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WIPO ähnelt.
        /// </summary>
        internal static string WO {
            get {
                return ResourceManager.GetString("WO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Samoa ähnelt.
        /// </summary>
        internal static string WS {
            get {
                return ResourceManager.GetString("WS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Other Country in Asia ähnelt.
        /// </summary>
        internal static string X1 {
            get {
                return ResourceManager.GetString("X1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Other Country in North America ähnelt.
        /// </summary>
        internal static string X2 {
            get {
                return ResourceManager.GetString("X2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Other Country in South America ähnelt.
        /// </summary>
        internal static string X3 {
            get {
                return ResourceManager.GetString("X3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Other Country in Europe ähnelt.
        /// </summary>
        internal static string X4 {
            get {
                return ResourceManager.GetString("X4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Other Country In Oceania ähnelt.
        /// </summary>
        internal static string X5 {
            get {
                return ResourceManager.GetString("X5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Other Country in Africa ähnelt.
        /// </summary>
        internal static string X6 {
            get {
                return ResourceManager.GetString("X6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Other Country ähnelt.
        /// </summary>
        internal static string XX {
            get {
                return ResourceManager.GetString("XX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Republic of Yemen ähnelt.
        /// </summary>
        internal static string YD {
            get {
                return ResourceManager.GetString("YD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yemen ähnelt.
        /// </summary>
        internal static string YE {
            get {
                return ResourceManager.GetString("YE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yugoslavia ähnelt.
        /// </summary>
        internal static string YU {
            get {
                return ResourceManager.GetString("YU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die South Africa ähnelt.
        /// </summary>
        internal static string ZA {
            get {
                return ResourceManager.GetString("ZA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zambia ähnelt.
        /// </summary>
        internal static string ZM {
            get {
                return ResourceManager.GetString("ZM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zaire ähnelt.
        /// </summary>
        internal static string ZR {
            get {
                return ResourceManager.GetString("ZR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zimbabwe ähnelt.
        /// </summary>
        internal static string ZW {
            get {
                return ResourceManager.GetString("ZW", resourceCulture);
            }
        }
    }
}
